# **DataFrame Operations**

In [1]:
import numpy as np
import pandas as pd

### **6-weather.xlsx**

In [4]:
weather_df = pd.read_excel('6-weather.xlsx')
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [5]:
weather_df.head() #ilk 5 satır

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [7]:
weather_df.tail() #son 5 satır

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [8]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [9]:
weather_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [10]:
weather_df.count()

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [11]:
weather_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

### **6-weatherna.xlsx**

In [32]:
#eksik veriler

In [12]:
weather_na_df = pd.read_excel('6-weatherna.xlsx')
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [14]:
weather_na_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [13]:
weather_na_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   8 non-null      float64
 1   New York   8 non-null      float64
 2   Amsterdam  8 non-null      float64
 3   Paris      6 non-null      float64
dtypes: float64(4)
memory usage: 420.0 bytes

In [15]:
weather_na_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [16]:
weather_na_df["Paris"].isna()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8     True
Name: Paris, dtype: bool

In [17]:
weather_na_df["Istanbul"].count()

np.int64(8)

In [19]:
weather_na_df.dropna() #bir satırda en az bir nan varsa komple siler

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [21]:
weather_na_df.dropna(axis=1)  #bir sütunda en az bir nan varsa komple siler

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [26]:
weather_na_df.drop('Paris', axis=1)

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [28]:
weather_na_df.fillna(20) #nan değerleri verilen değer ile doldurur

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0       20.0   14.0
2      20.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0      20.0       22.0   20.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0   20.0
8      22.0      16.0       16.0   20.0

In [30]:
weather_na_df.mean()

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [31]:
weather_na_df.fillna(weather_na_df.mean())

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

### **6-employee.csv**

In [33]:
#groupby

In [35]:
df = pd.read_csv('6-employee.csv')
df.head(10)

  Department Employee  Salary  Experience           City
0  Marketing    Emp_1   53483           1       New York
1      Sales    Emp_2   78555           8         Austin
2    Finance    Emp_3   47159           3         Austin
3      Sales    Emp_4  110077           3  San Francisco
4      Sales    Emp_5   65920           1       New York
5         IT    Emp_6   97121          11        Chicago
6    Finance    Emp_7   99479           5        Chicago
7    Finance    Emp_8  119475          10       New York
8    Finance    Emp_9   49457           7        Chicago
9      Sales   Emp_10   96557          10        Chicago

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  50 non-null     object
 1   Employee    50 non-null     object
 2   Salary      50 non-null     int64
 3   Experience  50 non-null     int64
 4   City        50 non-null     object
dtypes: int64(2), object(3)
memory usage: 2.1+ KB

In [39]:
df.describe() #numeric verilerde çalışır

              Salary  Experience
count      50.000000   50.000000
mean    78344.500000    7.060000
std     27817.603904    3.966235
min     31016.000000    1.000000
25%     53687.250000    3.000000
50%     78769.500000    7.000000
75%    100778.000000   10.000000
max    119812.000000   14.000000

In [44]:
df[df['Experience']>6].count()

Department    30
Employee      30
Salary        30
Experience    30
City          30
dtype: int64

In [45]:
df.groupby("Department")

In [46]:
df_grouped = df.groupby("Department")
df_grouped.count()

            Employee  Salary  Experience  City
Department
Finance           10      10          10    10
HR                 7       7           7     7
IT                10      10          10    10
Marketing         13      13          13    13
Sales             10      10          10    10

In [47]:
df_grouped.describe()

           Salary                                                          \
            count          mean           std      min       25%      50%
Department
Finance      10.0  90552.700000  27228.231832  47159.0  73222.00  96591.5
HR            7.0  76182.571429  31647.523983  31016.0  55114.50  78984.0
IT           10.0  63381.600000  24272.881041  32568.0  39755.25  66681.5
Marketing    13.0  79555.000000  28431.207129  39268.0  54300.00  70774.0
Sales        10.0  81038.900000  26623.181534  38571.0  68987.50  80775.0

                                Experience                                \
                  75%       max      count      mean       std  min  25%
Department
Finance     111836.75  119812.0       10.0  6.500000  3.566822  1.0  3.5
HR           96630.00  119789.0        7.0  8.714286  4.572173  3.0  5.0
IT           79850.00   97121.0       10.0  9.000000  4.163332  1.0  7.5
Marketing   104065.00  117538.0       13.0  6.153846  4.079341  1.0  3.0
Sales       100047.50  116779.0       10.0  5.700000  3.093003  1.0  3.5


             50%    75%   max
Department
Finance      6.5   9.50  12.0
HR           9.0  12.50  14.0
IT          10.5  11.75  14.0
Marketing    5.0   9.00  14.0
Sales        7.0   7.75  10.0

In [49]:
df_grouped_city = df.groupby("City")
df_grouped_city ["Salary"].mean()

City
Austin           81216.000000
Chicago          76869.363636
New York         70484.133333
San Francisco    87144.727273
Name: Salary, dtype: float64

In [50]:
df_grouped_city ["Salary"].describe()

,count,mean,std,min,25%,50%,75%,max
City,,,,,,,,
Austin,13.0,81216.000000,27010.770975,38571.0,54300.0,78555.0,104065.0,119812.0
Chicago,11.0,76869.363636,23718.116389,39692.0,59278.0,81214.0,96839.0,102409.0
New York,15.0,70484.133333,33208.693076,31016.0,38396.0,68044.0,95092.0,119789.0
San Francisco,11.0,87144.727273,24874.543739,39268.0,68731.0,91228.0,105644.0,116807.0

### **7-concat_data1.csv / 7-concat_data2.csv**

In [51]:
df1 = pd.read_csv("7-concat_data1.csv")
df1

   Employee_ID    Name Department
0            1   Emp_1    Finance
1            2   Emp_2  Marketing
2            3   Emp_3         HR
3            4   Emp_4    Finance
4            5   Emp_5    Finance
5            6   Emp_6  Marketing
6            7   Emp_7         HR
7            8   Emp_8         HR
8            9   Emp_9    Finance
9           10  Emp_10         IT

In [52]:
df2 = pd.read_csv("7-concat_data2.csv")
df2

   Employee_ID    Name Department
0           11  Emp_11    Finance
1           12  Emp_12    Finance
2           13  Emp_13    Finance
3           14  Emp_14    Finance
4           15  Emp_15  Marketing
5           16  Emp_16         HR
6           17  Emp_17  Marketing
7           18  Emp_18  Marketing
8           19  Emp_19  Marketing
9           20  Emp_20    Finance

In [53]:
#concat

In [54]:
df_concat = pd.concat([df1, df2], ignore_index = True)
df_concat

    Employee_ID    Name Department
0             1   Emp_1    Finance
1             2   Emp_2  Marketing
2             3   Emp_3         HR
3             4   Emp_4    Finance
4             5   Emp_5    Finance
5             6   Emp_6  Marketing
6             7   Emp_7         HR
7             8   Emp_8         HR
8             9   Emp_9    Finance
9            10  Emp_10         IT
10           11  Emp_11    Finance
11           12  Emp_12    Finance
12           13  Emp_13    Finance
13           14  Emp_14    Finance
14           15  Emp_15  Marketing
15           16  Emp_16         HR
16           17  Emp_17  Marketing
17           18  Emp_18  Marketing
18           19  Emp_19  Marketing
19           20  Emp_20    Finance

### **7-merge_data1.csv / 7-merge_data2.csv**

In [55]:
#merge

In [56]:
df_merge1 = pd.read_csv("7-merge_data1.csv")
df_merge1

   Employee_ID    Name Department
0            1   Emp_1         IT
1            2   Emp_2         HR
2            3   Emp_3         IT
3            4   Emp_4  Marketing
4            5   Emp_5  Marketing
5            6   Emp_6         IT
6            7   Emp_7         IT
7            8   Emp_8         IT
8            9   Emp_9  Marketing
9           10  Emp_10  Marketing

In [57]:
df_merge2 = pd.read_csv("7-merge_data2.csv")
df_merge2

   Employee_ID  Salary  Experience
0            5   55658           3
1            1  114478           5
2           12   48431          19
3           10   32747           7
4            6   89150           9
5           13   95725           7
6            9   65773           4
7           11   86886          18

In [58]:
#merge - outer join

In [59]:
df_merged_outer = pd.merge(df_merge1, df_merge2, on="Employee_ID", how="outer")
df_merged_outer

    Employee_ID    Name Department    Salary  Experience
0             1   Emp_1         IT  114478.0         5.0
1             2   Emp_2         HR       NaN         NaN
2             3   Emp_3         IT       NaN         NaN
3             4   Emp_4  Marketing       NaN         NaN
4             5   Emp_5  Marketing   55658.0         3.0
5             6   Emp_6         IT   89150.0         9.0
6             7   Emp_7         IT       NaN         NaN
7             8   Emp_8         IT       NaN         NaN
8             9   Emp_9  Marketing   65773.0         4.0
9            10  Emp_10  Marketing   32747.0         7.0
10           11     NaN        NaN   86886.0        18.0
11           12     NaN        NaN   48431.0        19.0
12           13     NaN        NaN   95725.0         7.0

In [ ]:
#merge - left join

In [60]:
df_merged_left = pd.merge(df_merge1, df_merge2, on="Employee_ID", how="left")
df_merged_left

   Employee_ID    Name Department    Salary  Experience
0            1   Emp_1         IT  114478.0         5.0
1            2   Emp_2         HR       NaN         NaN
2            3   Emp_3         IT       NaN         NaN
3            4   Emp_4  Marketing       NaN         NaN
4            5   Emp_5  Marketing   55658.0         3.0
5            6   Emp_6         IT   89150.0         9.0
6            7   Emp_7         IT       NaN         NaN
7            8   Emp_8         IT       NaN         NaN
8            9   Emp_9  Marketing   65773.0         4.0
9           10  Emp_10  Marketing   32747.0         7.0

In [61]:
#merge - right join

In [62]:
df_merged_right = pd.merge(df_merge1, df_merge2, on="Employee_ID", how="right")
df_merged_right

   Employee_ID    Name Department  Salary  Experience
0            5   Emp_5  Marketing   55658           3
1            1   Emp_1         IT  114478           5
2           12     NaN        NaN   48431          19
3           10  Emp_10  Marketing   32747           7
4            6   Emp_6         IT   89150           9
5           13     NaN        NaN   95725           7
6            9   Emp_9  Marketing   65773           4
7           11     NaN        NaN   86886          18

In [63]:
#merge - inner join

In [64]:
df_merged_inner = pd.merge(df_merge1, df_merge2, on="Employee_ID", how="inner")
df_merged_inner

   Employee_ID    Name Department  Salary  Experience
0            1   Emp_1         IT  114478           5
1            5   Emp_5  Marketing   55658           3
2            6   Emp_6         IT   89150           9
3            9   Emp_9  Marketing   65773           4
4           10  Emp_10  Marketing   32747           7

### **8-apply_function_data.csv**

In [65]:
df = pd.read_csv("8-apply_function_data.csv")
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [66]:
df.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [67]:
df.tail()

    Employee_ID     Name Department  Salary  Experience  Performance_Score
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

In [68]:
df.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [70]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience',
       'Performance_Score'],
      dtype='object')

In [75]:
df[1:10]

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
1,2,Emp_2,Sales,52662,24,3,medium
2,3,Emp_3,Finance,38392,5,3,low
3,4,Emp_4,Sales,60535,20,3,medium
4,5,Emp_5,Sales,108603,2,2,high
5,6,Emp_6,IT,82256,6,5,high
6,7,Emp_7,Finance,119135,22,1,high
7,8,Emp_8,Finance,65222,11,4,medium
8,9,Emp_9,Finance,107373,16,1,high
9,10,Emp_10,Sales,109575,16,5,high

In [72]:
def salary_category(salary):
    if salary<50000:
        return "low"
    elif 50000<=salary<80000:
        return "medium"
    else:
        return "high"

In [73]:
df["Salary"].apply(salary_category)

0       high
1     medium
2        low
3     medium
4       high
       ...
95      high
96      high
97      high
98       low
99    medium
Name: Salary, Length: 100, dtype: object

In [74]:
df["Salary_Category"] = df["Salary"].apply(salary_category)
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,high
1,2,Emp_2,Sales,52662,24,3,medium
2,3,Emp_3,Finance,38392,5,3,low
3,4,Emp_4,Sales,60535,20,3,medium
4,5,Emp_5,Sales,108603,2,2,high
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high
96,97,Emp_97,Sales,100467,22,2,high
97,98,Emp_98,IT,82662,23,3,high
98,99,Emp_99,IT,42688,22,1,low
99,100,Emp_100,HR,55342,14,3,medium

In [ ]:
# if experience > 10 -> performance_score + 1

In [84]:
def adjust_performance(experience):
    if experience > 10:
        return 1
    else:
        return 0

In [85]:
df["Experience"].apply(performance)

0     0
1     1
2     0
3     1
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: Experience, Length: 100, dtype: int64

In [86]:
df["Adjusted"] = df["Experience"].apply(performance)

In [87]:
df["new_score"] = df["Adjusted"] + df["Performance_Score"]
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,new_score
0,1,Emp_1,Marketing,82251,6,5,high,0,5
1,2,Emp_2,Sales,52662,24,3,medium,1,4
2,3,Emp_3,Finance,38392,5,3,low,0,3
3,4,Emp_4,Sales,60535,20,3,medium,1,4
4,5,Emp_5,Sales,108603,2,2,high,0,2
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,1,5
96,97,Emp_97,Sales,100467,22,2,high,1,3
97,98,Emp_98,IT,82662,23,3,high,1,4
98,99,Emp_99,IT,42688,22,1,low,1,2
99,100,Emp_100,HR,55342,14,3,medium,1,4

In [89]:
def adjust_new(row):
    if row["Experience"] >10:
        return row["Performance_Score"] + 1
    else:
        return row["Performance_Score"]

In [90]:
df["Adjusted_Score"] = df.apply(adjust_new, axis=1)
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,new_score,Adjusted_Score
0,1,Emp_1,Marketing,82251,6,5,high,0,5,5
1,2,Emp_2,Sales,52662,24,3,medium,1,4,4
2,3,Emp_3,Finance,38392,5,3,low,0,3,3
3,4,Emp_4,Sales,60535,20,3,medium,1,4,4
4,5,Emp_5,Sales,108603,2,2,high,0,2,2
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,1,5,5
96,97,Emp_97,Sales,100467,22,2,high,1,3,3
97,98,Emp_98,IT,82662,23,3,high,1,4,4
98,99,Emp_99,IT,42688,22,1,low,1,2,2
99,100,Emp_100,HR,55342,14,3,medium,1,4,4

In [93]:
df["Formatted_Name"] = df["Name"].apply(lambda x: x.replace("_"," "))
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,new_score,Adjusted_Score,Formatted_Name
0,1,Emp_1,Marketing,82251,6,5,high,0,5,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,medium,1,4,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,low,0,3,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,medium,1,4,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,high,0,2,2,Emp 5
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,1,5,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,high,1,3,3,Emp 97
97,98,Emp_98,IT,82662,23,3,high,1,4,4,Emp 98
98,99,Emp_99,IT,42688,22,1,low,1,2,2,Emp 99
99,100,Emp_100,HR,55342,14,3,medium,1,4,4,Emp 100